spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "033413"
    url: jdbc:mysql://localhost:3306/bbsSystem?serverTimezonge=UTC$useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.cheng.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081


